import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { NavigationMenu } from "@/components/NavigationMenu";
import "./globals.css";

// Root app shell: global fonts, global CSS, and persistent navigation.

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// TODO: replace default metadata before production rollout.
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavigationMenu />
        {children}
      </body>
    </html>
  );
}
